spring:
  application:
    name: news-source-db

  cloud:
    config:
      uri: http://172.16.213.27:8888

  config:
    import: "optional:configserver:"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true